oopt-goldstone/goldstone-mgmt

.github/workflows/ci.yaml
Makefile

add github action

---

.github/workflows/ci.yaml
.gitignore
Makefile
docker/builder.Dockerfile

refactor build

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
docker/builder.Dockerfile
src/north/cli/gscli/base.py
src/north/cli/gscli/main.py
src/north/cli/gscli/onlp.py
src/north/cli/gscli/tai.py

required for notification support

north/cli: move to async based

---

Makefile
docker/debug.Dockerfile
docker/run.Dockerfile

build: update

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
Makefile
docker/builder.Dockerfile
docker/run.Dockerfile
k8s/mgmt.yaml

ci: change docker repo

---

.github/workflows/publish.yaml
Makefile

ci: fix publish

---

src/south/tai/main.cpp

south/tai: fix bug of arg handling

---

src/south/onlp/main.cpp

south/onlp: use SR_SUBSCR_OPER_MERGE to merge pull/push oper data

---

k8s/mgmt.yaml
src/north/cli/gscli/tai.py

tai: fix pyang import

---

src/south/tai/main.cpp

module name can be normal string

tai: support non-int module name

---

docker/builder.Dockerfile
docker/run.Dockerfile
patches/libyang-python/add_get()_method_to_keyed_list.patch
patches/libyang-python/dup.patch
patches/libyang-python/fix-to-dnode.patch
patches/libyang-python/notification.patch
patches/libyang-python/series
patches/series
patches/sysrepo-python/add_more_info_to_oper_callback.patch
patches/sysrepo-python/add_oper_merge_subscribe_flag.patch
patches/sysrepo-python/async.patch
patches/sysrepo-python/notification.patch
patches/sysrepo-python/series
src/north/cli/gscli/tai.py
src/south/taipy/gstai/main.py
src/south/taipy/setup.py
tools/mk_quilt_patch.py

- support sysrepo notification feature in Python
- async notification support
- update sm/oopt-tai
- fix libyang-python
- install TAI shell python library in the builder
- patch sysrepo-python
- add a tool to create patches for submodules
- update sysrepo/libyang
- patch libyang-python to add get() method to KeyedList
- update sm/oopt-tai
- add Python TAI south daemon
- north/cli/tai: create missing parents when setting items
- build: use Python TAI south instead of C++ TAI south daemon

add Python based TAI south daemon

---

patches/libyang-python/add_sgrouping.patch
patches/libyang-python/series
patches/series
patches/sysrepo-python/add_copy_config.patch
patches/sysrepo-python/series
src/north/cli/gscli/main.py
src/north/cli/gscli/sonic.py
src/north/cli/gscli/tai.py
src/north/cli/setup.py
src/south/taipy/gstai/main.py
tools/mk_quilt_patch.py

- sm/sysrepo-python: add copy_config
- south/tai: better exception handling
- north/cli: add global show/save commands
- north/tai: fix a bug of operational data callback
- tools: fix mk_quilt_patch
- sm/libyang-python: add SGrouping
- norch/cli: remove pyang dependency

add global show/save commands

---

k8s/mgmt.yaml
patches/series
patches/sysrepo-python/add_lock_unlock.patch
patches/sysrepo-python/series
src/south/onlp/controller.hpp
src/south/onlp/main.cpp
src/south/taipy/gstai/main.py
tools/mk_quilt_patch.py

- sm/sysrepo-python: add lock/unlock
- update submodules
- south/onlp: set description of modules
- south/tai: implement start-up reconcile process
- k8s: don't create TAI objects automatically

south/tai: implement start-up reconcile process

---

.github/workflows/ci.yaml
patches/series
patches/sysrepo-python/add_sr_get_lock.patch
patches/sysrepo-python/series

sm/sysrepo-python: support sr_get_lock()

---

.github/workflows/push.yaml

ci: add missing 'secrets: inherit' in push.yaml

---

.github/workflows/ci.yaml
.github/workflows/push.yaml
.gitmodules
Makefile
docker/agent.Dockerfile
docker/builder.Dockerfile
k8s/north-gnmi.yaml
scripts/gnmi-supported-models.json
src/north/gnmi/Makefile
src/north/gnmi/README.md
src/north/gnmi/goldstone/north/gnmi/main.py
src/north/gnmi/goldstone/north/gnmi/repo/repo.py
src/north/gnmi/goldstone/north/gnmi/repo/sysrepo.py
src/north/gnmi/goldstone/north/gnmi/server.py
src/north/gnmi/requirements.txt
src/north/gnmi/requirements_dev.txt
src/north/gnmi/setup.py
src/north/gnmi/tests/gnmi-supported-models.json
src/north/gnmi/tests/lib.py
src/north/gnmi/tests/test.py
src/north/gnmi/tests/test_gnmi.py

This PR adds a [gNMI](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md) server application as `north/gnmi`. The server will provide users with a gRPC-based interface for control and management.
If #56 is merged first, commit 6cfabc805d94ee551f97dbff63f0f98b3c63e83e will be removed.

Add gNMI server

---

docker/agent.Dockerfile

build: cross-compile rust builder for speed up

---

src/north/cli/goldstone/north/cli/main.py
src/north/cli/tests/test_main.py

north/cli: fix wrong import

---

src/south/system/requirements.txt

south/system: fix missing requirements

---

.github/workflows/ci.yaml
.github/workflows/push.yaml
Makefile
docker/agent.Dockerfile
docker/builder.Dockerfile
k8s/south-ocnos.yaml
scripts/gs-yang.py
src/south/ocnos/MANIFEST.in
src/south/ocnos/data/feature-list.yang
src/south/ocnos/goldstone/south/ocnos/interfaces.py
src/south/ocnos/goldstone/south/ocnos/main.py
src/south/ocnos/goldstone/south/ocnos/ocnos.py
src/south/ocnos/goldstone/south/ocnos/util.py
src/south/ocnos/goldstone/south/ocnos/vlan.py
src/south/ocnos/requirements.txt
src/south/ocnos/setup.py
src/south/ocnos/tests/mock_ocnos.py
src/south/ocnos/tests/test_interface.py
src/south/ocnos/tests/test_vlan.py

This PR adds new agent called `south-ocnos`.
The `south-ocnos` is one of Goldstone management south daemons that control switch ASIC by configuring containerized OcNOS.
It supports the interface and vlan configuration on the platform where containerized OcNOS is running.
This implementation is contributed by IP Infusion and NTT.

south/ocnos: initial support for configuring interface and vlan of containerized OcNOS

---

src/south/sonic/goldstone/south/sonic/interfaces.py

Description:
This change adds an enhancement to the UFD feature. It monitors the uplink port oper-status and toggles downlink admin status up/down, based on state. Fix with reference to the issue https://github.com/oopt-goldstone/goldstone-mgmt/issues/77.

UFD feature enhancement

---

src/north/cli/goldstone/north/cli/interface.py

Background:
https://github.com/oopt-goldstone/goldstone-mgmt/issues/81

fix: counter function
